// AUTO-GENERATED by scripts/compute-reading-times.py — do not edit by hand.
// Re-run that script after editing module content to keep estimates current.

export const readingTimes = {
  'attention-deeper': 35,
  'autograd-backprop': 26,
  'cuda-convolution': 57,
  'cuda-histogram-sort': 56,
  'cuda-intro-gpu': 53,
  'cuda-memory-model': 69,
  'cuda-mixed-precision': 12,
  'cuda-optimization-capstone': 65,
  'cuda-performance': 70,
  'cuda-programming-model': 57,
  'cuda-reduction': 66,
  'cuda-scan': 57,
  'cuda-sparse-graphs': 59,
  'cuda-streams-graphs': 14,
  'cuda-tensor-cores': 15,
  'cuda-thread-execution': 60,
  'cuda-tiling-matmul': 58,
  'inference-batching-vllm': 47,
  'llm-building-blocks': 29,
  'modern-llm-arch': 35,
  'moe-mla': 35,
  'mps-ane-coreml-profiling': 22,
  'mps-apple-gpu-architecture': 15,
  'mps-flash-attention': 13,
  'mps-metal-shaders': 27,
  'mps-mlx-framework': 24,
  'mps-tensor-fundamentals': 19,
  'nn-module-training': 43,
  'qkv-deep-dive': 26,
  'rl-snake': 37,
  'tensors-devices': 17,
  'tiny-transformer': 24,
  'training-inference-details': 32,
}

export function readingTimeFor(moduleId) {
  return readingTimes[moduleId] || null
}

// Sum reading time across all modules in a course. Returns minutes or null
// if no module has a known time. Used by the landing/course pages.
export function courseTotalMinutes(course) {
  if (!course?.modules) return null
  let total = 0; let known = 0
  for (const m of course.modules) {
    const t = readingTimes[m.id]
    if (typeof t === "number") { total += t; known++ }
  }
  return known > 0 ? total : null
}

// Format minutes as a compact human string: "47 min", "1h 32m", "5h".
export function formatMinutes(min) {
  if (!min || min <= 0) return ""
  if (min < 60) return min + " min"
  const h = Math.floor(min / 60)
  const m = min % 60
  return m === 0 ? (h + "h") : (h + "h " + m + "m")
}
