#!/usr/bin/env python3
"""Compute reading-time estimates for every module JSON and emit a
generated JS file mapping moduleId -> minutes.

Re-run whenever module content changes substantially:
    python3 scripts/compute-reading-times.py

The output is `src/content/reading-times.js`. Imported by App.jsx and
ModulePage.jsx so the course-page module cards can show "12 min read"
without loading each module's full content.
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONTENT_DIRS = [
    ROOT / 'src' / 'content' / 'modules',
    ROOT / 'src' / 'content' / 'cuda-modules',
    ROOT / 'src' / 'content' / 'mps-modules',
]
OUT = ROOT / 'src' / 'content' / 'reading-times.js'

# Technical reading is ~800 chars/min; we use 850 to be slightly generous.
# This matches the on-the-fly estimator in ModulePage.estimateReadingMinutes.
CHARS_PER_MINUTE = 850

def chars_of_module(d):
    """Total readable characters across a module's sections + code."""
    total = 0
    for s in d.get('sections', []):
        total += len(s.get('content', ''))
        total += len(s.get('code', ''))
    return total

def main():
    times = {}
    files = []
    for d in CONTENT_DIRS:
        if not d.exists():
            continue
        files.extend(sorted(d.glob('*.json')))

    for path in files:
        try:
            data = json.loads(path.read_text())
        except json.JSONDecodeError as e:
            print(f'  ! skipping {path.name}: {e}')
            continue
        mid = data.get('id')
        if not mid:
            continue
        chars = chars_of_module(data)
        minutes = max(1, round(chars / CHARS_PER_MINUTE))
        times[mid] = minutes
        print(f'  {mid:40s} {chars:6d} chars -> {minutes:3d} min')

    # Emit JS file.
    lines = [
        '// AUTO-GENERATED by scripts/compute-reading-times.py — do not edit by hand.',
        '// Re-run that script after editing module content to keep estimates current.',
        '',
        'export const readingTimes = {',
    ]
    for mid in sorted(times):
        lines.append(f"  '{mid}': {times[mid]},")
    lines.append('}')
    lines.append('')
    lines.append('export function readingTimeFor(moduleId) {')
    lines.append('  return readingTimes[moduleId] || null')
    lines.append('}')
    lines.append('')
    lines.append('// Sum reading time across all modules in a course. Returns minutes or null')
    lines.append('// if no module has a known time. Used by the landing/course pages.')
    lines.append('export function courseTotalMinutes(course) {')
    lines.append('  if (!course?.modules) return null')
    lines.append('  let total = 0; let known = 0')
    lines.append('  for (const m of course.modules) {')
    lines.append('    const t = readingTimes[m.id]')
    lines.append('    if (typeof t === "number") { total += t; known++ }')
    lines.append('  }')
    lines.append('  return known > 0 ? total : null')
    lines.append('}')
    lines.append('')
    lines.append('// Format minutes as a compact human string: "47 min", "1h 32m", "5h".')
    lines.append('export function formatMinutes(min) {')
    lines.append('  if (!min || min <= 0) return ""')
    lines.append('  if (min < 60) return min + " min"')
    lines.append('  const h = Math.floor(min / 60)')
    lines.append('  const m = min % 60')
    lines.append('  return m === 0 ? (h + "h") : (h + "h " + m + "m")')
    lines.append('}')
    lines.append('')
    OUT.write_text('\n'.join(lines))
    print(f'\nWrote {OUT} ({len(times)} modules)')

if __name__ == '__main__':
    main()
